-- Run once in Supabase Dashboard > SQL Editor.
-- This adds Stock Inventory snapshots only. It does not alter pallet_slots,
-- receive_dates, Zone geometry, or any floor-plan data.

create table if not exists public.stock_inventory_snapshots (
  id bigint generated by default as identity primary key,
  report_date text not null,
  source_name text not null,
  stock_data jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.stock_inventory_snapshots enable row level security;
revoke all on public.stock_inventory_snapshots from anon, authenticated;

create extension if not exists pgcrypto;

create table if not exists public.stock_inventory_settings (
  singleton boolean primary key default true check (singleton),
  pin_hash text,
  updated_at timestamptz not null default now()
);

insert into public.stock_inventory_settings(singleton, pin_hash)
values (true, null)
on conflict (singleton) do nothing;

alter table public.stock_inventory_settings enable row level security;
revoke all on public.stock_inventory_settings from anon, authenticated;

create or replace function public.replace_stock_inventory(
  p_report_date text,
  p_source_name text,
  p_items jsonb,
  p_update_pin text
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  stock_result jsonb;
  configured_pin_hash text;
begin
  select pin_hash into configured_pin_hash
  from public.stock_inventory_settings where singleton = true;

  if configured_pin_hash is null then
    raise exception 'Update PIN is not configured';
  end if;

  if crypt(coalesce(p_update_pin, ''), configured_pin_hash) <> configured_pin_hash then
    raise exception 'Invalid Update PIN';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Stock inventory must contain at least one item';
  end if;

  if jsonb_array_length(p_items) > 20000 then
    raise exception 'Stock inventory exceeds 20,000 rows';
  end if;

  with item_rows as materialized (
    select
      left(trim(x.code), 80) as code,
      left(trim(x.name), 500) as name,
      left(coalesce(trim(x.unit), ''), 80) as unit,
      coalesce(x.qty, 0)::numeric as qty,
      coalesce(x.value, 0)::numeric as value,
      left(trim(x.wh), 30) as wh,
      left(coalesce(nullif(trim(x.cat), ''), 'อื่นๆ'), 120) as cat,
      x.ord
    from rows from (
      jsonb_to_recordset(p_items) as (
        code text, name text, unit text, qty numeric, value numeric, wh text, cat text
      )
    ) with ordinality as x(code, name, unit, qty, value, wh, cat, ord)
    where trim(coalesce(x.code, '')) <> ''
      and trim(coalesce(x.name, '')) <> ''
      and trim(coalesce(x.wh, '')) <> ''
  ), totals as (
    select coalesce(sum(value),0) total_value, coalesce(sum(qty),0) total_qty,
           count(*) total_rows, count(distinct code) unique_skus,
           count(distinct wh) warehouse_count, count(distinct cat) category_count
    from item_rows
  ), wh_rows as (
    select wh code,
      case wh
        when '200' then 'บรรจุภัณฑ์และแพ็คเกจจิ้งงานระหว่างทำ อยู่ไลท์ผลิต BCL'
        when '201' then 'บรรจุภัณฑ์และแพ็คเกจจิ้ง-นครชัยศรี'
        when '202' then 'บรรจุภัณฑ์และแพ็คเกจจิ้ง-OEM'
        when '204' then 'บรรจุภัณฑ์และแพ็คเกจจิ้ง-ลูกค้า'
        when '401' then 'คลังนำกลับมาใช้ใหม่-บรรจุภัณฑ์'
        when '800' then 'คลัง Hold'
        when '900' then 'คลัง รอทำลาย'
        else 'คลัง ' || wh end as name,
      case wh when '200' then 'PD - งานระหว่างทำ BCL' when '201' then 'BW - นครชัยศรี'
        when '202' then 'BCL - OEM' when '204' then 'ลูกค้าฝาก' when '401' then 'นำกลับมาใช้ใหม่'
        when '800' then 'Hold' when '900' then 'รอทำลาย' else wh end as short,
      case wh when '200' then 'Preparation' when '201' then 'BW' when '202' then 'OEM'
        when '204' then 'Customer' when '401' then 'Re-work' when '800' then 'Hold'
        when '900' then 'Reject' else wh end as en_label,
      count(*) items, sum(qty) qty, sum(value) value, bool_or(value <> 0) has_value
    from item_rows group by wh
  ), cat_rows as (
    select cat label, sum(value) value, sum(qty) qty, count(distinct code) items
    from item_rows group by cat
  ), code_rows as (
    select code, min(name) name, min(unit) unit, sum(qty) qty, sum(value) value,
      jsonb_agg(distinct wh order by wh) whs
    from item_rows group by code
  ), neg_rows as (
    select code, name, value, wh from item_rows where value < 0 order by value asc limit 8
  )
  select jsonb_build_object(
    'report_date', left(coalesce(nullif(trim(p_report_date), ''), 'ไม่ระบุวันที่'), 120),
    'kpis', jsonb_build_object(
      'total_value', t.total_value, 'total_qty', t.total_qty, 'total_rows', t.total_rows,
      'unique_skus', t.unique_skus, 'warehouse_count', t.warehouse_count,
      'category_count', t.category_count
    ),
    'warehouses', coalesce((select jsonb_agg(jsonb_build_object(
      'code', w.code, 'name', w.name, 'short', w.short, 'en_label', w.en_label,
      'items', w.items, 'qty', w.qty, 'value', w.value,
      'pct', case when t.total_value = 0 then 0 else round(w.value / t.total_value * 100, 2) end,
      'has_value', w.has_value) order by w.value desc) from wh_rows w), '[]'::jsonb),
    'categories', coalesce((select jsonb_agg(jsonb_build_object(
      'label', c.label, 'value', c.value, 'qty', c.qty, 'items', c.items,
      'pct', case when t.total_value = 0 then 0 else c.value / t.total_value * 100 end)
      order by c.value desc) from cat_rows c), '[]'::jsonb),
    'top_items', coalesce((select jsonb_agg(to_jsonb(z) order by z.value desc) from
      (select code, name, unit, qty, value, whs from code_rows order by value desc limit 15) z), '[]'::jsonb),
    'data_quality', jsonb_build_object(
      'neg_count', (select count(*) from item_rows where value < 0),
      'neg_sum', (select coalesce(sum(value),0) from item_rows where value < 0),
      'neg_items', coalesce((select jsonb_agg(to_jsonb(n) order by n.value asc) from neg_rows n), '[]'::jsonb),
      'unmatched_rows', 0,
      'no_value_warehouses', coalesce((select jsonb_agg(code order by code) from wh_rows where not has_value), '[]'::jsonb)
    ),
    'items', coalesce((select jsonb_agg(jsonb_build_object(
      'code', code, 'name', name, 'unit', unit, 'qty', qty, 'value', value,
      'wh', wh, 'cat', cat) order by ord) from item_rows), '[]'::jsonb)
  ) into stock_result
  from totals t;

  insert into public.stock_inventory_snapshots(report_date, source_name, stock_data)
  values (left(coalesce(p_report_date, 'ไม่ระบุวันที่'), 120), left(coalesce(p_source_name, 'manual upload'), 500), stock_result);

  return stock_result;
end;
$$;

create or replace function public.get_latest_stock_inventory()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select stock_data from public.stock_inventory_snapshots order by id desc limit 1;
$$;

revoke all on function public.replace_stock_inventory(text, text, jsonb, text) from public;
revoke all on function public.get_latest_stock_inventory() from public;
grant execute on function public.replace_stock_inventory(text, text, jsonb, text) to anon, authenticated;
grant execute on function public.get_latest_stock_inventory() to anon, authenticated;

-- Ask PostgREST to refresh its schema cache immediately after installing/updating RPCs.
notify pgrst, 'reload schema';

-- REQUIRED: replace the text below with a private PIN before running this statement.
-- Never put the PIN in index.html or commit it to GitHub.
-- update public.stock_inventory_settings
-- set pin_hash = extensions.crypt('YOUR-PRIVATE-PIN', extensions.gen_salt('bf')), updated_at = now()
-- where singleton = true;
