const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {resolveScan,locationPayload,productPayload} = require('../barcode-operations.js');
const locations = [{zone:'G',slot:'G-06'},{zone:'G-1',slot:'G1-06'}];
const products = [{code:'31-0001-01',name:'ขวด',barcode:'8851234567890'},{code:'31-0001-02',name:'ฝา'}];
assert.deepEqual(resolveScan(locationPayload('G','G-06'),locations,products),{kind:'location',zone:'G',slot:'G-06'});
assert.equal(resolveScan('G-06',locations,products).kind,'location');
assert.equal(resolveScan(productPayload('31-0001-01'),locations,products).product.code,'31-0001-01');
assert.equal(resolveScan('8851234567890',locations,products).product.code,'31-0001-01');
assert.equal(resolveScan('31-0001',locations,products).kind,'invalid','partial SKU must not select a product');
assert.equal(resolveScan('PKLOC|G|BAD',locations,products).kind,'invalid');
assert.equal(resolveScan('PKLOC||G-06',locations,products).reason,'รูปแบบ QR ไม่ถูกต้อง');
assert.equal(resolveScan('PKITEM|',locations,products).reason,'รูปแบบ QR ไม่ถูกต้อง');
assert.equal(resolveScan('PKITEM|31-0001-02',locations,products).product.code,'31-0001-02');
const storedTagId = '123e4567-e89b-42d3-a456-426614174000';
assert.deepEqual(resolveScan(`PKTAG|${storedTagId.toUpperCase()}`,locations,products),{kind:'tag',id:storedTagId});
assert.equal(resolveScan('PKTAG|not-a-uuid',locations,products).kind,'invalid');
assert.equal(resolveScan('G-06',[...locations,{zone:'X',slot:'G-06'}],products).kind,'invalid','ambiguous physical label must be rejected');
const ui = fs.readFileSync(path.join(__dirname,'..','barcode-ui.js'),'utf8');
const html = fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
assert.match(ui,/openSlotEdit\(zone,slot\)/);
assert.match(ui,/renderSearchMatches\(matches, productCode, false\)/,'a product scan must show all pallet positions immediately');
assert.match(ui,/from\('incoming_pallets'\)[\s\S]*?from\('pallet_slots'\)/,'a stored pallet tag must load its current slot before opening the issue form');
assert.match(ui,/jumpToSlot\(location\.zone,location\.slot\);[\s\S]*?openSlotEdit\(location\.zone,location\.slot\)/,'a stored pallet tag must open its slot and product list');
assert.match(ui,/dataset\.tab !== 'floorplan'/,'the camera belongs to the floor-plan tab');
assert.match(ui,/await stopCamera\(\); clearSelection\(false\)/,'completed scans must not leak into the next scan');
assert.match(ui,/scanBusy/,'camera callbacks must be guarded against overlapping scans');
assert.match(ui,/cameraGeneration/,'camera startup must be cancellable when the tab closes or a scan completes');
assert.match(ui,/barcodeScanClear/,'operators need an explicit way to discard an incorrect scan');
assert.match(html,/id="pane-floorplan"[\s\S]*?id="barcodeTitle"[\s\S]*?id="floorplanSearch"/,'scanner must be embedded before the floor-plan search');
assert.match(html,/id="tab-print-labels"[^>]*data-tab="print-labels"[^>]*aria-controls="pane-print-labels"/,'label printing needs its own menu tab');
assert.match(html,/id="pane-print-labels"[\s\S]*?id="barcodePrintZone"[\s\S]*?id="barcodePrintLocations"[\s\S]*?id="barcodePrintProductCode"[\s\S]*?id="barcodePrintProduct"[\s\S]*?id="barcodePrintStatus"[\s\S]*?id="pane-incoming"/,'both print controls and their status must live in the new panel');
assert.equal((html.match(/id="barcodePrintZone"/g)||[]).length,1,'the print controls must not remain duplicated in the floor-plan scanner');
assert.match(ui,/function printMessage\([\s\S]*?printStatus\.textContent/,'print errors must be visible in the new tab');
assert.doesNotMatch(html,/id="tab-barcode"|id="pane-barcode"/,'scanner must not remain as a separate menu tab');
assert.match(html,/jumpToSlot\(link\.dataset\.zone, link\.dataset\.slot\);\s*openSlotEdit\(link\.dataset\.zone, link\.dataset\.slot\);/,
  'selecting a scanned product position must open its item list');
assert.doesNotMatch(ui,/savePalletBatch|runSlotMutation/,'scan must not change stock until the user reviews and saves');
console.log('PASS: exact product/location scans, alias matching, ambiguity rejection and reviewed writes');
