const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const names = ['bomNumber', 'normalizeBomUnit', 'bomComponentType', 'bomConversion', 'calculateBomPlan'];
const source = names.map(n => html.match(new RegExp(`function ${n}\\([^]*?\\n\\}`))[0]).join('\n');
const ctx = vm.createContext({ BOM_COMPONENT_TYPES:{}, BOM_UNIT_CONVERSIONS:[] });
vm.runInContext(source, ctx);
const line = (code='SHARED', usage=2, unit='ใบ') => ({pk_code:code,pk_name:code,unit,qty_per_unit:usage,component_type:'packaging'});
const stock = (qty=10,unit='ใบ',wh='200') => ({code:'SHARED',qty,unit,wh});
let details = {A:{lines:[line()]},B:{lines:[line('SHARED',3)]}};
const entries = [{fg:'A',qty:3},{fg:'B',qty:2}], items = [stock(),stock(999,'ใบ','800'),stock(999,'ใบ','900')];
const before = JSON.stringify({details,entries,items});
let result = ctx.calculateBomPlan(entries,details,items,['800','900']);
assert.equal(result.rows.length,1);
assert.equal(result.rows[0].required,12);
assert.equal(result.rows[0].available,10,'Shared supply counted once, excluding hold/reject');
assert.equal(result.rows[0].shortage,2);
assert.equal(result.ready,false,'Individually feasible FGs can be jointly infeasible');
assert.equal(JSON.stringify({details,entries,items}),before,'Planner does not mutate inventory or standard BOM');
result = ctx.calculateBomPlan([{fg:'A',qty:2},{fg:'B',qty:2}],details,items,['800','900']);
assert.equal(result.ready,true);
assert.equal(result.rows[0].remaining,0);
details.A.lines.push(line('SHARED',1));
result = ctx.calculateBomPlan([{fg:'A',qty:3}],details,[stock()],[]);
assert.equal(result.rows[0].required,9,'Repeated component lines within a formula are summed');
for (const qty of ['',0,-1,Infinity,'abc']) {
  result = ctx.calculateBomPlan([{fg:'A',qty}],details,[stock()],[]);
  assert.equal(result.ready,false); assert.equal(result.errors.length,1);
}
assert.equal(ctx.calculateBomPlan([],details,[],[]).ready,false);
assert.equal(ctx.calculateBomPlan([{fg:'missing',qty:1}],details,[],[]).ready,false);
details = {A:{lines:[line('SHARED',1,'ม้วน')]},B:{lines:[line('SHARED',2,'ใบ')]}};
result = ctx.calculateBomPlan(entries,details,[stock(2,'ม้วน')],[]);
assert.equal(result.ready,false); assert.equal(result.unknown,1);
assert.equal(result.rows[0].required,null,'Missing unit conversion cannot produce a partial demand total');
ctx.BOM_UNIT_CONVERSIONS.push({code:'SHARED',from:'ม้วน',to:'ใบ',factor:100,source:'Approved synthetic test'});
result = ctx.calculateBomPlan(entries,details,[stock(4,'ม้วน')],[]);
assert.equal(result.ready,true); assert.equal(result.rows[0].required,304); assert.equal(result.rows[0].available,400);
const reverse = ctx.calculateBomPlan([...entries].reverse(),details,[stock(4,'ม้วน')],[]);
assert.equal(reverse.rows[0].unit,result.rows[0].unit); assert.equal(reverse.rows[0].required,304);
details.A.lines[0].component_type = 'unknown';
assert.equal(ctx.calculateBomPlan(entries,details,[stock(4,'ม้วน')],[]).ready,false);
details.A.lines[0].component_type = 'non_packaging';
assert.equal(ctx.calculateBomPlan(entries,details,[stock(4,'ม้วน')],[]).errors.length,1,'Empty packaging formula remains unknown');
details = {A:{lines:[line()]}};
assert.equal(ctx.calculateBomPlan([{fg:'A',qty:1}],details,[stock(null)],[]).rows[0].available,null);
assert.equal(ctx.calculateBomPlan([{fg:'A',qty:1}],details,[],[]).rows[0].shortage,2);
console.log('PASS: shared demand, repeated components, units, exclusions, unknown data and non-mutating plan');
