const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
global.PKBarcode=require('../barcode-operations.js');
const incoming=require('../incoming-workflow.js');
const id='550e8400-e29b-41d4-a716-446655440000';
assert.equal(incoming.tagPayload(id),`PKTAG|${id}`);
assert.equal(incoming.parseTag(`pKtag|${id.toUpperCase()}`),id);
for(const invalid of ['',id,'PKTAG|','PKTAG|not-a-uuid',`PKTAG|${id}|extra`]) assert.equal(incoming.parseTag(invalid),null);
const products=[{code:'31-0007-05-5502',name:'ฝาปั๊ม',unit:'ชิ้น'},{code:'31-0007-05-5502',name:'ฝาปั๊ม',unit:'ชิ้น'}];
assert.equal(incoming.exactProduct('PKITEM|31-0007-05-5502',products).code,'31-0007-05-5502');
assert.equal(incoming.exactProduct('31-0007',products),null,'partial codes must never create a receipt');
const locations=[{zone:'G',slot:'G-02'},{zone:'G',slot:'G-06'}];
assert.deepEqual(incoming.exactLocation('PKLOC|G|G-02',locations),{zone:'G',slot:'G-02'});
assert.equal(incoming.exactLocation('G-0',locations),null,'partial locations must never complete putaway');
assert.deepEqual(incoming.distributeQuantity(3072,10),[308,308,307,307,307,307,307,307,307,307]);
assert.equal(incoming.distributeQuantity(1,3),null,'whole units cannot be split across more pallets than pieces');
assert.deepEqual(incoming.distributeQuantity(1.001,2),[0.501,0.5]);
assert.equal(incoming.distributeQuantity(1,2),null,'no pallet may have zero quantity');
assert.equal(incoming.validAllocation(3072,[308,308,307,307,307,307,307,307,307,307]),true);
assert.equal(incoming.validAllocation(3072,[307,307]),false,'the edited pallet quantities must equal the receipt total');
const sql=fs.readFileSync(path.join(__dirname,'..','supabase-incoming.sql'),'utf8');
assert.match(sql,/request_id uuid not null unique/,'retrying a receipt must not create a second tag');
assert.match(sql,/where id=p_tag_id for update[\s\S]*tag\.status <> 'pending'/,'one tag must be put away only once');
assert.match(sql,/public\.incoming_locations loc where loc\.zone=target_zone and loc\.slot_code=target_slot/,'database must reject an unknown location without ambiguous column names');
assert.doesNotMatch(sql,/\bslot_code\s+text\s*:=/,'PL/pgSQL local variables must not shadow table columns');
assert.match(sql,/insert into public\.pallet_slots[\s\S]*update public\.incoming_pallets set status='stored'/,'stock and tag status must change in one transaction');
const locs=[...sql.matchAll(/\('[A-Z][A-Z0-9-]*','[A-Z][A-Z0-9-]*',2,(\d+)\)/g)];
assert.equal(locs.length,40);
assert.equal(locs.reduce((count,match)=>count+Number(match[1]),0),1001,'all mapped floor-plan locations must be available for putaway');
const batchSql=fs.readFileSync(path.join(__dirname,'..','supabase-incoming-batches.sql'),'utf8');
assert.match(batchSql,/create unique index if not exists incoming_pallets_batch_index_idx/);
assert.match(batchSql,/total_from_tags <> p_total_quantity/);
assert.match(batchSql,/for i in 1\.\.p_pallet_count loop[\s\S]*insert into public\.incoming_pallets/);
assert.match(batchSql,/pg_catalog\.jsonb_agg\(to_jsonb\(tag\) order by tag\.batch_index\)/);
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
assert.match(html,/id="incomingPalletCount"/);
assert.match(html,/4 ใบ\/หน้า/);
assert.match(html,/id="incomingWorkflowTabs"[\s\S]*data-incoming-view="receive"[\s\S]*data-incoming-view="putaway"[\s\S]*data-incoming-view="history"/,'receive, putaway and recent tags must be distinct views');
const ui=fs.readFileSync(path.join(__dirname,'..','incoming-ui.js'),'utf8');
assert.match(ui,/rpc\('create_incoming_batch'/,'the receipt form must create all pallet tags as one batch');
assert.match(ui,/i\+=4/,'print sheets must contain at most four labels');
assert.match(ui,/showIncomingView\('putaway',true\);selectTag/,'choosing a pending tag should open the putaway view');
assert.match(ui,/grid-template-columns:repeat\(2,1fr\).*grid-template-rows:repeat\(2,1fr\)/,'labels must print in a 2 by 2 A4 grid');
console.log('PASS: FM-ST-011/019 exact scans, unique tags, single putaway and location catalog');
