const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
global.PKBarcode=require('../barcode-operations.js');
const incoming=require('../incoming-workflow.js');
const id='550e8400-e29b-41d4-a716-446655440000';
assert.equal(incoming.tagPayload(id),`PKTAG|${id}`);
assert.equal(incoming.parseTag(`pKtag|${id.toUpperCase()}`),id);
for(const invalid of ['',id,'PKTAG|','PKTAG|not-a-uuid',`PKTAG|${id}|extra`]) assert.equal(incoming.parseTag(invalid),null);
const products=[{code:'31-0007-05-5502',name:'ฝาปั๊ม',unit:'ชิ้น'},{code:'31-0007-05-5502',name:'ฝาปั๊ม',unit:'ชิ้น'}];
assert.equal(incoming.exactProduct('PKITEM|31-0007-05-5502',products).code,'31-0007-05-5502');
assert.equal(incoming.exactProduct('31-0007',products),null,'partial codes must never create a receipt');
const locations=[{zone:'G',slot:'G-02'},{zone:'G',slot:'G-06'}];
assert.deepEqual(incoming.exactLocation('PKLOC|G|G-02',locations),{zone:'G',slot:'G-02'});
assert.equal(incoming.exactLocation('G-0',locations),null,'partial locations must never complete putaway');
const sql=fs.readFileSync(path.join(__dirname,'..','supabase-incoming.sql'),'utf8');
assert.match(sql,/request_id uuid not null unique/,'retrying a receipt must not create a second tag');
assert.match(sql,/where id=p_tag_id for update[\s\S]*tag\.status <> 'pending'/,'one tag must be put away only once');
assert.match(sql,/public\.incoming_locations where zone=zone_code and slot_code=slot_code/,'database must reject an unknown location');
assert.match(sql,/insert into public\.pallet_slots[\s\S]*update public\.incoming_pallets set status='stored'/,'stock and tag status must change in one transaction');
const locs=[...sql.matchAll(/\('[A-Z][A-Z0-9-]*','[A-Z][A-Z0-9-]*',2,(\d+)\)/g)];
assert.equal(locs.length,40);
assert.equal(locs.reduce((count,match)=>count+Number(match[1]),0),1001,'all mapped floor-plan locations must be available for putaway');
console.log('PASS: FM-ST-011/019 exact scans, unique tags, single putaway and location catalog');
