const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const extract = name => html.match(new RegExp(`function ${name}\\([^]*?\\n\\}`))[0];
const ctx = vm.createContext({SLOT_ITEMS:{A:{'A-01':[]}}});
vm.runInContext(['formatMovementDate','getRemainingQty','movementNumber','movementDateKey','getStockMovement','buildSlotMovePlan','updateSlotItem'].map(extract).join('\n'),ctx);

const original = {code:'PK-01',name:'ขวด',lotNo:'2609-1',receiveDate:'2026-09-01',unit:'ขวด',qty:100,remainingQty:70,
  withdrawals:[{date:'2026-09-03',qty:30,unit:'ขวด',by:'คลัง'}]};
const source = {zone:'A',slot_code:'A-01',occupied:true,items:[original,{code:'PK-02',qty:20,remainingQty:20,unit:'ใบ'}]};
const destination = {zone:'A',slot_code:'A-02',occupied:true,items:[{code:'OLD',qty:5,remainingQty:5,unit:'ใบ'}]};
const before = JSON.stringify({source,destination});
const plan = ctx.buildSlotMovePlan(source,destination,[{index:0,qty:'25',whole:false}], '2026-09-15','สมชาย');
assert.equal(plan.source.items.length,2);
assert.equal(plan.destination.items.length,2,'Destination items remain in place');
assert.equal(plan.source.items[0].remainingQty,45);
assert.equal(plan.destination.items[1].remainingQty,25);
assert.equal(plan.destination.items[1].qty,0);
assert.equal(ctx.getStockMovement(plan.source.items[0]).computed,45);
assert.equal(ctx.getStockMovement(plan.destination.items[1]).computed,25);
assert.equal(ctx.getStockMovement(plan.source.items[0]).mismatch,false);
assert.equal(ctx.getStockMovement(plan.destination.items[1]).mismatch,false);
assert.equal(plan.source.items[0].transfersOut[0].to,'A/A-02');
assert.equal(plan.destination.items[1].transfersIn[0].from,'A/A-01');
assert.equal(JSON.stringify({source,destination}),before,'Preparing the move cannot change unsaved data');
ctx.SLOT_ITEMS.A['A-01']=[plan.source.items[0]];
assert.equal(ctx.updateSlotItem('A','A-01',0,{...plan.source.items[0],qty:110}),true);
assert.equal(plan.source.items[0].remainingQty,55,'Editing receipts still accounts for transferred stock');
const whole = ctx.buildSlotMovePlan(source,destination,[{index:0,qty:'70',whole:false},{index:1,whole:true}], '2026-09-15','สมชาย');
assert.equal(whole.source.occupied,false);
assert.equal(whole.source.items.length,0);
assert.equal(whole.destination.items.length,3);
assert.equal(whole.destination.items[1].withdrawals[0].qty,30,'Full relocation preserves item history');
assert.equal(whole.destination.items[1].locationMoves[0].from,'A/A-01');
assert.equal(ctx.getStockMovement(whole.destination.items[1]).computed,70);
const unknown = {zone:'A',slot_code:'A-03',occupied:true,items:[{code:'UNKNOWN'}]};
assert.equal(ctx.buildSlotMovePlan(unknown,destination,[{index:0,whole:true}], '2026-09-15','สมชาย').movedCount,1);
assert.throws(()=>ctx.buildSlotMovePlan(unknown,destination,[{index:0,qty:1}], '2026-09-15','สมชาย'),/จำนวนย้าย/);
for (const bad of [0,-1,71,NaN]) assert.throws(()=>ctx.buildSlotMovePlan(source,destination,[{index:0,qty:bad}], '2026-09-15','สมชาย'),/จำนวนย้าย/);
assert.throws(()=>ctx.buildSlotMovePlan(source,source,[{index:0,whole:true}], '2026-09-15','สมชาย'),/คนละตำแหน่ง/);
assert.throws(()=>ctx.buildSlotMovePlan(source,destination,[], '2026-09-15','สมชาย'),/เลือกสินค้า/);
assert.throws(()=>ctx.buildSlotMovePlan(source,destination,[{index:2,whole:true}], '2026-09-15','สมชาย'),/รายการที่เลือก/);
assert.throws(()=>ctx.buildSlotMovePlan(source,destination,[{index:0,whole:true},{index:0,whole:true}], '2026-09-15','สมชาย'),/รายการที่เลือก/);
assert.throws(()=>ctx.buildSlotMovePlan(source,destination,[{index:0,whole:true}], '2026-02-30','สมชาย'),/วันที่/);
assert.throws(()=>ctx.buildSlotMovePlan(source,destination,[{index:0,whole:true}], '2026-08-31','สมชาย'),/ก่อนวันที่รับเข้า/);
const mixedUnit = {zone:'A',slot_code:'A-09',occupied:true,items:[{...original,returns:[{date:'2026-09-04',qty:5,unit:'ลัง'}],remainingQty:75}]};
assert.throws(()=>ctx.buildSlotMovePlan(mixedUnit,destination,[{index:0,qty:5}], '2026-09-15','สมชาย'),/ยอดประวัติ/);
assert.throws(()=>ctx.buildSlotMovePlan(source,destination,[{index:0,whole:true}], '2026-09-15',''),/ผู้ย้าย/);
assert.match(html,/savePalletBatch\(\[\{\.\.\.plan\.source,expected_version:moveSourceVersion\},\{\.\.\.plan\.destination,expected_version:moveDestinationVersion\}\]\)/);
assert.match(html,/finally \{ palletWriteBusy = false; updateSlotMoveState\(true\); \}/,'Save errors remain visible after the request finishes');
assert.match(html,/id="fseMoveToggle"[^>]*aria-expanded="false"/);
console.log('PASS: whole/partial pallet moves, destination merge, stock-card transfers, validation and atomic save proposal');
