const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const names = ['getRemainingQty', 'summarizeSlotBalance', 'withdrawSlotItem', 'returnSlotItem'];
const source = names.map(name => html.match(new RegExp(`function ${name}\\([^]*?\\n\\}`))[0]).join('\n');
const ctx = vm.createContext({ SLOT_ITEMS: { F: { 'F-18': [] } }, syncSlotToRemote() {} });
vm.runInContext(source, ctx);
const sample = { qty: 21, unit: 'ม้วน' };
ctx.SLOT_ITEMS.F['F-18'].push(sample);
ctx.withdrawSlotItem('F', 'F-18', 0, { qty: 9 });
ctx.withdrawSlotItem('F', 'F-18', 0, { qty: 1 });
assert.equal(ctx.summarizeSlotBalance([sample]).totals[0].qty, 11);
ctx.returnSlotItem('F', 'F-18', 0, { qty: 3 });
assert.equal(ctx.summarizeSlotBalance([sample]).totals[0].qty, 14);
const input = [sample, { qty: '2.5', unit: 'ม้วน' }, { remainingQty: 0, qty: 99, unit: 'ขวด' },
  { qty: 5, unit: 'ขวด' }, { qty: 2 }, { unit: 'ขวด' }, { qty: '' }, { qty: 'invalid' }];
const before = JSON.stringify(input);
const result = JSON.parse(JSON.stringify(ctx.summarizeSlotBalance(input)));
assert.deepEqual(result, { totals: [{ unit: 'ม้วน', qty: 16.5 }, { unit: 'ขวด', qty: 5 }, { unit: '', qty: 2 }], unknown: 3 });
assert.equal(JSON.stringify(input), before, 'Aggregation must not mutate items');
assert.equal(ctx.summarizeSlotBalance([]).totals.length, 0);
assert.equal(ctx.summarizeSlotBalance([{ qty: 0 }]).totals[0].qty, 0);
assert.match(html, /sm-receive/);
assert.match(html, /sm-withdraw/);
assert.match(html, /sm-return/);
assert.match(html, /renderSlotBalance\(items\);/);
const summaryStyle = html.match(/\.fse-balance-summary \{([^]*?)\}/)[1];
assert.match(summaryStyle, /margin: 10px 0 10px auto/);
assert.match(summaryStyle, /max-width: 100%/);
assert.match(summaryStyle, /justify-content: flex-end/);
assert.match(summaryStyle, /background: var\(--series-1-wash\)/);
assert.match(summaryStyle, /text-align: right/);
console.log('PASS: receive/withdraw/return balances, mixed units, unknown/zero balances, non-mutating summary');
