const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const render = html.match(/function renderZoneSelector\([^]*?\n\}/)[0];
const escape = html.match(/function escapeHtml\([^]*?\n\}/)[0];
const map = JSON.parse(html.match(/const FLOOR_ZONE_MAP = (\{[^\n]+\});/)[1]);
map.U = map['U-1']; delete map['U-1'];
const entries = Object.entries(map);
const before = JSON.stringify(entries);
const result = vm.runInNewContext(`${escape}\n(${render})(entries)`, { entries });
const labels = [...result.matchAll(/<button\b[^>]*>([^<]+)<\/button>/g)].map(m => m[1]);
assert.equal(labels.length, 46);
assert.equal(new Set(labels).size, 46);
assert.deepEqual([...labels].sort(), Object.keys(map).sort());
assert.ok(labels.every(x => /^[A-Z](?:-1)?$/.test(x)), 'Only zone codes, no pallet identifiers');
assert.ok(labels.includes('C') && labels.includes('U') && labels.includes('T-1') && labels.includes('Z-1'));
assert.equal((result.match(/aria-pressed="false"/g) || []).length, 46);
assert.equal(JSON.stringify(entries), before);
console.log('PASS: all 46 unique zones, no pallet codes, accessible buttons, source order unchanged');
